export const pathPrefix = "path";

export enum EnumComponentName {
  ActionSheet = "ActionSheet",
  ActionSheetItem = "ActionSheetItem",
  AtActionSheetItem="AtActionSheetItem",
  ActivityIndicator = "ActivityIndicator",
  Avatar = "Avatar",
  Badge = "Badge",
  Button = "Button",
  Card = "Card",
  Checkbox = "Checkbox",
  Drawer = "Drawer",
  Fab = "Fab",
  FloatLayout = "FloatLayout",
  Form = "Form",
  Grid = "Grid",
  Icon = "Icon",
  InputNumber = "InputNumber",
  Input = "Input",
  ListItem = "ListItem",
  List = "List",
  Modal = "Modal",
  NavBar = "NavBar",
  Noticebar = "Noticebar",
  Pagination = "Pagination",
  Progress = "Progress",
  Radio = "Radio",
  Rate = "Rate",
  SegmentedControl = "SegmentedControl",
  Switch = "Switch",
  SearchBar = "SearchBar",
  TabBar = "TabBar",
  Tabs = "Tabs",
  Tag = "Tag",
  Textarea = "Textarea",
  Timeline = "Timeline",
  Toast = "Toast",
  TabsPane = "TabsPane",
  SwipeAction = "SwipeAction",
  Accordion = "Accordion",
  LoadMore = "LoadMore",
  Divider = "Divider",
  Countdown = "Countdown",
  Steps = "Steps",
  Curtain = "Curtain",
  Slider = "Slider",
  Message = "Message",
  ImagePicker = "ImagePicker",
  Indexes = "Indexes",
  Range = "Range",
  FloatButton = "FloatButton",
  Calendar = "Calendar",
  ListItemText = "ListItemText",
  ListItemInput = "ListItemInput",
  ListItemTextarea = "ListItemTextarea",
  ListItemSwitch = "ListItemSwitch",
  ListItemRadio = "ListItemRadio",
  ListItemCheckbox = "ListItemCheckbox",
  ListItemFile = "ListItemFile",
  ListItemFiles = "ListItemFiles",
  AtInput = "AtInput",
  AtTextarea = "AtTextarea"
}

const ComponentNames = Object.values(EnumComponentName);

const TaroUIComponentNames = [
  "ActionSheet",
  "ActionSheetItem",
  "ActivityIndicator",
  "Avatar",
  "Badge",
  "Button",
  "Card",
  "Checkbox",
  "Drawer",
  "Fab",
  "FloatLayout",
  "Form",
  "Grid",
  "Icon",
  "InputNumber",
  "Input",
  "ListItem",
  "List",
  "Modal",
  "NavBar",
  "Noticebar",
  "Pagination",
  "Progress",
  "Radio",
  "Rate",
  "SegmentedControl",
  "Switch",
  "SearchBar",
  "TabBar",
  "Tabs",
  "Tag",
  "Textarea",
  "Timeline",
  "Toast",
  "TabsPane",
  "SwipeAction",
  "Accordion",
  "LoadMore",
  "Divider",
  "Countdown",
  "Steps",
  "Curtain",
  "Slider",
  "Message",
  "ImagePicker",
  "Indexes",
  "Range",
  "FloatButton",
  "Calendar"
];

export function isTaroUI(name: string): boolean {
  return TaroUIComponentNames.includes(name);
}
