export const pathPrefix = "path";

export enum EnumComponentName {
  AtActionSheet = "AtActionSheet",
  AtActionSheetItem = "AtActionSheetItem",
  AtActivityIndicator = "AtActivityIndicator",
  AtAvatar = "AtAvatar",
  AtBadge = "AtBadge",
  AtButton = "AtButton",
  AtCard = "AtCard",
  AtCheckbox = "AtCheckbox",
  AtDrawer = "AtDrawer",
  AtFab = "AtFab",
  AtFloatLayout = "AtFloatLayout",
  AtForm = "AtForm",
  AtGrid = "AtGrid",
  AtIcon = "AtIcon",
  AtInputNumber = "AtInputNumber",
  AtInput = "AtInput",
  AtListItem = "AtListItem",
  AtList = "AtList",
  AtModal = "AtModal",
  AtNavBar = "AtNavBar",
  AtNoticebar = "AtNoticebar",
  AtPagination = "AtPagination",
  AtProgress = "AtProgress",
  AtRadio = "AtRadio",
  AtRate = "AtRate",
  AtSegmentedControl = "AtSegmentedControl",
  AtSwitch = "AtSwitch",
  AtSearchBar = "AtSearchBar",
  AtTabBar = "AtTabBar",
  AtTabs = "AtTabs",
  AtTag = "AtTag",
  AtTextarea = "AtTextarea",
  AtTimeline = "AtTimeline",
  AtToast = "AtToast",
  AtTabsPane = "AtTabsPane",
  AtSwipeAction = "AtSwipeAction",
  AtAccordion = "AtAccordion",
  AtLoadMore = "AtLoadMore",
  AtDivider = "AtDivider",
  AtCountdown = "AtCountdown",
  AtSteps = "AtSteps",
  AtCurtain = "AtCurtain",
  AtSlider = "AtSlider",
  AtMessage = "AtMessage",
  AtImagePicker = "AtImagePicker",
  AtIndexes = "AtIndexes",
  AtRange = "AtRange",
  AtFloatButton = "AtFloatButton",
  AtCalendar = "AtCalendar",
  AtListItemText = "AtListItemText",
  AtListItemInput = "AtListItemInput",
  AtListItemTextarea = "AtListItemTextarea",
  AtListItemSwitch = "AtListItemSwitch",
  AtListItemRadio = "AtListItemRadio",
  AtListItemCheckbox = "AtListItemCheckbox",
  AtListItemFile = "AtListItemFile",
  AtListItemFiles = "AtListItemFiles",
  AtAtInput = "AtAtInput",
  AtAtTextarea = "AtAtTextarea"
}

const ComponentNames = Object.values(EnumComponentName);

const TaroUIComponentNames = [
  "ActionSheet",
  "ActionSheetItem",
  "ActivityIndicator",
  "Avatar",
  "Badge",
  "Button",
  "Card",
  "Checkbox",
  "Drawer",
  "Fab",
  "FloatLayout",
  "Form",
  "Grid",
  "Icon",
  "InputNumber",
  "Input",
  "ListItem",
  "List",
  "Modal",
  "NavBar",
  "Noticebar",
  "Pagination",
  "Progress",
  "Radio",
  "Rate",
  "SegmentedControl",
  "Switch",
  "SearchBar",
  "TabBar",
  "Tabs",
  "Tag",
  "Textarea",
  "Timeline",
  "Toast",
  "TabsPane",
  "SwipeAction",
  "Accordion",
  "LoadMore",
  "Divider",
  "Countdown",
  "Steps",
  "Curtain",
  "Slider",
  "Message",
  "ImagePicker",
  "Indexes",
  "Range",
  "FloatButton",
  "Calendar"
];

export function isTaroUI(name: string): boolean {
  return TaroUIComponentNames.includes(name);
}
